on:
  push:

jobs:
  build:
    runs-on: "${{ matrix.runs-on }}"
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - "ubuntu-latest"
          - "windows-latest"
        php-version:
          - "7.4"
          - "8.0"
        ts:
          - "ts"
          - "nts"
        exclude:
          - runs-on: "ubuntu-latest"
            ts: ts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: intl
        env:
          phpts: "${{ matrix.ts }}"

      - name: "Install phpstan deps"
        env:
          COMPOSER_ROOT_VERSION: "0.12.x-dev"
        run: |
          composer install

      - name: "Clone & install test repo"
        run: |
          cd repro
          git clone https://github.com/atk4/ui.git && cd ui
          composer install

      - name: "Run PHPStan"
        run: |
          cd repro/ui
          php --version
          php ../../bin/phpstan clear-result-cache
          php -d memory_limit=2G ../../bin/phpstan analyse --ansi --debug --verbose

      - name: "Run PHPStan /w opcache enabled for CLI"
        run: |
          cd repro/ui
          php --version
          php ../../bin/phpstan clear-result-cache
          php -d memory_limit=2G -d opcache.enable=1 -d opcache.enable_cli=1 ../../bin/phpstan analyse --ansi --debug --verbose
